src/Entity/SubReddit.php
<?php

namespace App\Entity;

use App\Entity\SubReddit\Wallpaper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SubRedditRepository")
 */
class SubReddit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SubReddit\Wallpaper", mappedBy="subreddit")
     */
    private $wallpapers;

    public function __construct()
    {
        $this->wallpapers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Wallpaper[]
     */
    public function getWallpapers(): Collection
    {
        return $this->wallpapers;
    }

    public function addWallpaper(Wallpaper $wallpaper): self
    {
        if (!$this->wallpapers->contains($wallpaper)) {
            $this->wallpapers[] = $wallpaper;
            $wallpaper->setSubreddit($this);
        }

        return $this;
    }

    public function removeWallpaper(Wallpaper $wallpaper): self
    {
        if ($this->wallpapers->contains($wallpaper)) {
            $this->wallpapers->removeElement($wallpaper);
            // set the owning side to null (unless already changed)
            if ($wallpaper->getSubreddit() === $this) {
                $wallpaper->setSubreddit(null);
            }
        }

        return $this;
    }

    public function getNumUnrated() {
        $numUnratedWallpapers = count($this->wallpapers);
        foreach ($this->wallpapers as $wallpaper) {
            if ($wallpaper->getRating() !== 0) {
                $numUnratedWallpapers--;
            }
        }

        return $numUnratedWallpapers;
    }

    public function getNumFavourites() {
        $numFavouriteWallpapers = count($this->wallpapers);
        foreach ($this->wallpapers as $wallpaper) {
            if ($wallpaper->getRating() <= 0) {
                $numFavouriteWallpapers--;
            }
        }

        return $numFavouriteWallpapers;
    }
}

src/Entity/SubReddit/Wallpaper.php
<?php

namespace App\Entity\SubReddit;

use App\Entity\SubReddit;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SubReddit\WallpaperRepository")
 */
class Wallpaper
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SubReddit", inversedBy="wallpapers")
     */
    private $subreddit;

    /**
     * @ORM\Column(type="string", length=64, unique=true)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    public function __construct(
      SubReddit $subreddit,
      $imageUrl,
      $permaLink,
      $title
    ) {
        $this->subreddit = $subreddit;
        $this->url = $permaLink;
        $this->hash = hash('sha256', $imageUrl);
        $this->title = $title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubreddit(): ?SubReddit
    {
        return $this->subreddit;
    }

    public function setSubreddit(?SubReddit $subreddit): self
    {
        $this->subreddit = $subreddit;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getImageUrl()
    {
        return '/subreddits/'.$this->subreddit->getName().'/'.$this->hash;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
}

src/Controller/WallpaperController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Process\Process;
use Symfony\Component\Routing\Annotation\Route;

class WallpaperController extends AbstractController
{

    /**
     * The path to the downloader lock file
     *
     * @var string
     */
    protected $downloaderLockFile = '/public/downloader.lock';

    /**
     * The download timeout, in seconds.
     *
     * @var int
     */
    protected $downloaderTimeoutSeconds = 600;

    /**
     * Are we currently downloading wallpapers?
     *
     * @return bool
     */
    protected function isDownloading()
    {
        return file_exists($this->getParameter(
            'kernel.project_dir'
          ).$this->downloaderLockFile);
    }

    /**
     * @Route("/", name="root")
     */
    public function root($id = null)
    {
        return $this->redirectToRoute('wallpaper');
    }

    /**
     * @Route("/wallpapers/{id}", name="wallpaper", defaults={"id": null})
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Exception
     */
    public function index($id = null)
    {
        $subreddits = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit::class)
          ->findAll();

        // Select a random subreddit
        if ($id === null) {
            $subreddit = $this->getDoctrine()
              ->getRepository(\App\Entity\SubReddit::class)
              ->findRandomUnrated();
            if (!$subreddit) {
                return $this->render(
                  'wallpaper/index.html.twig',
                  [
                    'subreddits' => $subreddits,
                    'wallpaper' => null,
                    'is_downloading' => $this->isDownloading(),
                  ]
                );
            }

            return $this->redirectToRoute(
              'wallpaper',
              ['id' => $subreddit->getId()]
            );
        }

        // Handle unknown subreddits
        $subreddit = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit::class)
          ->find($id);
        if (!$subreddit) {
            return $this->redirectToRoute('wallpaper');
        }

        /** @var \App\Entity\SubReddit\Wallpaper $wallpaper */
        $wallpaper = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit\Wallpaper::class)
          ->findFirstUnrated($id);
        if (!$wallpaper) {
            return $this->redirectToRoute('wallpaper');
        }

        return $this->render(
          'wallpaper/index.html.twig',
          [
            'subreddits' => $this->getDoctrine()
              ->getRepository(\App\Entity\SubReddit::class)
              ->findAll(),
            'wallpaper' => $wallpaper,
            'is_downloading' => $this->isDownloading(),
          ]
        );
    }

    /**
     * @Route("/favourite/{id}/{subredditId}", name="wallpaper_favourite")
     */
    public function favourite($id, $subredditId)
    {
        $wallpaper = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit\Wallpaper::class)
          ->find($id);
        if ($wallpaper !== null) {
            $wallpaper->setRating(1);
            $this->getDoctrine()
              ->getManager()
              ->persist($wallpaper);
            $this->getDoctrine()
              ->getManager()
              ->flush();
        }

        return $this->redirectToRoute('wallpaper', ['id' => $subredditId]);
    }

    /**
     * @Route("/reject/{id}/{subredditId}", name="wallpaper_reject")
     */
    public function reject($id, $subredditId)
    {
        $wallpaper = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit\Wallpaper::class)
          ->find($id);
        if ($wallpaper !== null) {
            $wallpaper->setRating(-1);
            $this->getDoctrine()
              ->getManager()
              ->persist($wallpaper);
            $this->getDoctrine()
              ->getManager()
              ->flush();

            $filesystem = new Filesystem();
            $imageFilePath = $this->getParameter(
                'kernel.project_dir'
              ).'/public'.$wallpaper->getImageUrl();
            $filesystem->remove($imageFilePath);
        }

        $returnUrl = $_GET['return_url'] ?? 'wallpaper';
        $pageNum = $_GET['page_num'] ?? null;

        return $this->redirectToRoute(
          $returnUrl,
          ['id' => $subredditId, 'pageNum' => $pageNum]
        );
    }


    /**
     * @Route("/set/{id}/{subredditId}", name="wallpaper_set")
     *
     * @throws \Exception
     */
    public function set($id, $subredditId, KernelInterface $kernel)
    {
        $wallpaper = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit\Wallpaper::class)
          ->find($id);
        if ($wallpaper !== null) {
            $application = new Application($kernel);
            $application->setAutoExit(false);

            $imageFilePath = $this->getParameter(
                'kernel.project_dir'
              ).'/public'.$wallpaper->getImageUrl();
            $input = new ArrayInput(
              [
                'command' => 'wallpaper:set',
                'input-file' => $imageFilePath,
                'watermark-text' => '/r/'.$wallpaper->getSubreddit()
                    ->getName(),
                'output-file' => getenv(
                    'HOME'
                  ).'/Pictures/Wallpaper/wallpaper.jpg',
              ]
            );

            $output = new NullOutput();
            $application->run($input, $output);
        }

        $returnUrl = $_GET['return_url'] ?? 'wallpaper';
        $pageNum = $_GET['page_num'] ?? null;

        return $this->redirectToRoute(
          $returnUrl,
          ['id' => $subredditId, 'pageNum' => $pageNum]
        );
    }

    /**
     * @Route("/favourites/{pageNum}", name="wallpaper_favourites",
     *   defaults={"pageNum": 1})
     *
     * @throws \Exception
     */
    public function favourites($pageNum = 1)
    {
        $wallpapersPerPage = 5;
        $numWallpapers = $this->getDoctrine()
          ->getRepository(
            \App\Entity\SubReddit\Wallpaper::class
          )
          ->findCountFavourites();
        $numPages = ceil($numWallpapers / $wallpapersPerPage);
        $wallpapers = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit\Wallpaper::class)
          ->findAllFavourites(
            $pageNum,
            $wallpapersPerPage
          );
        $subreddits = $this->getDoctrine()
          ->getRepository(\App\Entity\SubReddit::class)
          ->findAll();

        return $this->render(
          'wallpaper/favourites.html.twig',
          [
            'subreddits' => $subreddits,
            'wallpapers' => $wallpapers,
            'page_num' => $pageNum,
            'num_pages' => $numPages,
            'is_downloading' => $this->isDownloading(),
          ]
        );
    }

    /**
     * @Route("/wallpapers/downloader/start", name="wallpaper_downloader_start")
     */
    public function downloaderStart(KernelInterface $kernel)
    {
        $process = Process::fromShellCommandline(
          'nohup php ./bin/console wallpaper:download > /dev/null 2>&1 &',
          $this->getParameter('kernel.project_dir'),
          null,
          null,
          $this->downloaderTimeoutSeconds
        );
        $process->start();

        $response = new Response();
        $response->setContent("ok");

        return $response;
    }

    /**
     * @Route("/wallpapers/downloader/status", name="wallpaper_downloader_status")
     */
    public function downloaderStatus()
    {
        $downloaderLockFile = $this->getParameter(
            'kernel.project_dir'
          ).$this->downloaderLockFile;

        // Remove a stale lock file
        if (file_exists($downloaderLockFile) && filemtime(
            $downloaderLockFile
          ) < strtotime('now -'.$this->downloaderTimeoutSeconds.' seconds')) {
            unlink($downloaderLockFile);
        }

        if (file_exists($downloaderLockFile)) {
            $status = 'Running';
        } else {
            $status = 'Stopped';
        }

        $response = new Response();
        $response->setContent($status);

        return $response;
    }
}

templates/wallpaper/favourites.html.twig
{% extends 'base.html.twig' %}

{% block title %}RWAR!{% endblock %}

{% block toolbar %}
    <h4>Favourites</h4>
{% endblock %}

{% block sidebar %}
    {% for subreddit in subreddits %}
        /r/{{ subreddit.name }}
        {% set numFavourites = subreddit.numFavourites %}
        {% if numFavourites > 0 %}
            ({{ numFavourites }})
        {% endif %}
        <br>
    {% endfor %}
{% endblock %}

{% block body %}
    {% for wallpaper in wallpapers %}
        <a href="{{ wallpaper.url }}" target="_blank">
            <img alt="wallpaper" id="wallpaper-image" src="{{ wallpaper.imageUrl }}"
                 style="width: 100%; padding: 10px;"/>
        </a>
        <div style="text-align: center">
            <a id="link-reject"
               href="{{ url('wallpaper_reject', {id: wallpaper.id, subredditId: wallpaper.subreddit.id, return_url: 'wallpaper_favourites', page_num: page_num}) }}">Reject</a>
            |
            <a id="link-set"
               href="{{ url('wallpaper_set', {id: wallpaper.id, subredditId: wallpaper.subreddit.id, return_url: 'wallpaper_favourites', page_num: page_num}) }}">Set</a>
        </div>
    {% endfor %}

    <div style="text-align: center; margin-top: 20px">
        {% if page_num > 1 %}
            <a href="{{ url('wallpaper_favourites', {pageNum: (page_num - 1) }) }}">&laquo; Prev</a>
        {% else %}
            <span style="display: inline-block">&laquo; Prev</span>
        {% endif %}

        {% for i in 1..num_pages %}
            {% if i == page_num %}
                <span style="font-weight: bold; display: inline-block">{{ i }}</span>
            {% else %}
                <a href="{{ url('wallpaper_favourites', {pageNum: i}) }}">{{ i }}</a>
            {% endif %}
        {% endfor %}

        {% if page_num < num_pages %}
            <a href="{{ url('wallpaper_favourites', {pageNum: (page_num + 1) }) }}">Next &raquo;</a>
        {% else %}
            <span style="display: inline-block">Next &raquo;</span>
        {% endif %}
    </div>
{% endblock %}

templates/wallpaper/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RWAR!{% endblock %}

{% block toolbar %}
    {% if wallpaper %}
    <span style="display: inline-block">
        <a id="link-favourite"
           href="{{ url('wallpaper_favourite', {id: wallpaper.id, subredditId: wallpaper.subreddit.id}) }}">Favourite
            (w)
        </a>
        |
        <a id="link-reject"
           href="{{ url('wallpaper_reject', {id: wallpaper.id, subredditId: wallpaper.subreddit.id}) }}">Reject
            (s)
        </a>
        |
        <a id="link-set"
           href="{{ url('wallpaper_set', {id: wallpaper.id, subredditId: wallpaper.subreddit.id}) }}">Set
            (z)
        </a>
    </span>
    {% endif %}
{% endblock %}

{% block sidebar %}
    {% for subreddit in subreddits %}
        {% set numUnratedWallpapers = subreddit.numUnrated %}
        {% if numUnratedWallpapers > 0 %}
            <a href="{{ url('wallpaper', {id: subreddit.id}) }}"
                    {% if subreddit.id == wallpaper.subreddit.id %}
                        style="font-weight: bold"
                    {% endif %}
            >
                /r/{{ subreddit.name }}
            </a> ({{ numUnratedWallpapers }})<br>
        {% else %}
            /r/{{ subreddit.name }}<br>
        {% endif %}
    {% endfor %}
{% endblock %}

{% block body %}
    {% if not wallpaper %}
        <strong>No wallpapers found, please start the Downloader</strong>
    {% else %}
        <img alt="wallpaper" id="wallpaper-image" src="{{ wallpaper.imageUrl }}"
             style="width: 100%; padding: 10px;"/>
        <div id="image-source">
            {% if wallpaper.url|length > 0 %}
                <a href="{{ wallpaper.url }}" target="_blank">
                    {{ wallpaper.title }}
                </a>
            {% endif %}
        </div>
        <div id="image-resolution"></div>
    {% endif %}
{% endblock %}